on:
  - push
  - pull_request

name: Test and lint

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal:
          - 3.6
        ghc:
          - 9.2.5
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update $CONFIG
      - run: cabal v2-build $CONFIG
      - run: cabal v2-test $CONFIG
      - run: cabal v2-haddock $CONFIG
      - run: cabal v2-sdist

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up HLint'
        uses: haskell/actions/hlint-setup@v2

      - name: 'Run HLint'
        uses: haskell/actions/hlint-run@v2
        with:
          path: '["src/", "tests/", "app/"]'
          fail-on: warning
