on:
  - push
  - pull_request

name: Test and lint

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal:
          - 3.6
        ghc:
          - 8.10.7
          - 9.2.2
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: haskell/actions/setup@v1.2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update $CONFIG
      - run: cabal v2-build $CONFIG
      - run: cabal v2-test $CONFIG
      - run: cabal v2-haddock $CONFIG
      - run: cabal v2-sdist

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: 3.3.6

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: '["src/", "tests/", "app/"]'
        fail-on: warning
